version: "3.7"

services:
  # AUTH API
  server:
    container_name: auth_api
    build:
      context: ./auth-server/
      dockerfile: ./docker/Dockerfile
    working_dir: /usr/src/server
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    command: npm start
    restart: always
    # Using volumes overrides dockerignore..
    volumes:
      - ./auth-server/:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      DB_URI: ${DKR_DB_URI}
      JWT_SECRET: ${JWT_SECRET}

  # ws-server
  ws-server:
    container_name: ws_server
    build:
      context: ./chat-socket-server
      dockerfile: ./docker/Dockerfile
    working_dir: /usr/src/ws-server
    ports:
      - "8080:8080"
    #restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}

  # DB
  postgres:
    container_name: auth_db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    restart: always
    #Extract to file
    environment:
      POSTGRES_DB: ${DKR_PG_DB}
      POSTGRES_USER: "${DKR_PG_USER}"
      POSTGRES_PASSWORD: "${DKR_PG_PASSWORD}"
