version: "3.7"

services:
  # Backend API
  server:
    container_name: auth_api
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    working_dir: /usr/src/server
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    command: npm start
    restart: always
    # Using volumes overrides dockerignore..
    volumes:
      - ./:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      DB_URI: ${DB_URI}

  postgres:
    container_name: auth_db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    restart: always
    #Extract to file
    environment:
      POSTGRES_DB: ${DKR_PG_DB}
      POSTGRES_USER: "${DKR_PG_USER}"
      POSTGRES_PASSWORD: "${DKR_PG_PASSWORD}"
